export const GET_USER_LIST_REQUEST = "@movieListReducer/GET_USER_LIST_REQUEST ";
export const GET_USER_LIST_SUCCESS = "@movieListReducer/GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_FAIL = "@movieListReducer/GET_USER_LIST_FAIL";
export const GET_USER_DELETE_REQUEST = "@movieListReducer/GET_USER_DELETE_REQUEST ";
export const GET_USER_DELETE_SUCCESS = "@movieListReducer/GET_USER_DELETE_SUCCESS";
export const GET_USER_DELETE_FAIL = "@movieListReducer/GET_USER_DELETE_FAIL";
export const GET_USER_ADD_REQUEST = "@movieListReducer/GET_USER_ADD_REQUEST ";
export const GET_USER_ADD_SUCCESS = "@movieListReducer/GET_USER_ADD_SUCCESS";
export const GET_USER_ADD_FAIL = "@movieListReducer/GET_USER_ADD_FAIL";
