export const GET_MOVIE_MANAGEMENT_REQUEST = "@cinemaListReducer/GET_MOVIE_MANAGEMENT_REQUEST ";
export const GET_MOVIE_MANAGEMENT_SUCCESS = "@cinemaListReducer/GET_MOVIE_MANAGEMENT_SUCCESS";
export const GET_MOVIE_MANAGEMENT_FAIL = "@cinemaListReducer/GET_MOVIE_MANAGEMENT_FAIL";
