export const GET_TICKET_BOOKING_DETAILS_REQUEST =
  "@ticketBookingReducer/GET_TICKET_BOOKING_DETAILS_REQUEST";
export const GET_TICKET_BOOKING_DETAILS_SUCCESS =
  "ticketBookingReducer/GET_TICKET_BOOKING_DETAILS_SUCCESS";
export const GET_TICKET_BOOKING_DETAILS_FAIL =
  "@ticketBookingReducer/GET_TICKET_BOOKING_DETAILS_FAIL";
